# cursor = '|'
# blinking-cursor = false
option-as-alt = "right"
padding-x = 8
padding-y = [8, 8]

[window]
mode = "Maximized"

[editor]
program = "hx"
args = []

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[fonts]
family = "MonoLisa"
size = 14
[fonts.regular]
style = "Normal"
weight = 400
[fonts.bold]
style = "Normal"
weight = 700
[fonts.italic]
style = "Italic"
weight = 400
[fonts.bold-italic]
style = "Italic"
weight = 700
[fonts.emoji]
family = "Apple Color Emoji"

[colors]
foreground = "#ebebf5"
background = "#1e1e28"
selection-foreground = "#1e1e28"
selection-background = "#b8ccff"
cursor = "#e5e1f5"
# regular
black = "#44445a"
red = "#ff758C"
green = "#a8f5ba"
yellow = "#ffc97d"
blue = "#9bcaff"
magenta = "#ff9be3"
cyan = "#69fff6"
white = "#e5e1f5"
