theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
rulers = [80, 100]
bufferline = "multiple"
color-modes = true

[keys.normal]
";" = "command_mode"

[keys.insert]
j = {j = "normal_mode"}
k = {k = "normal_mode"}
