theme = "kanagawa"

[editor]
line-number = "relative"
cursorline = true
rulers = [80, 100]
bufferline = "multiple"
color-modes = true

[keys.normal]
";" = "command_mode"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-s = ":w"

[keys.insert]
j = {j = "normal_mode"}
k = {k = "normal_mode"}
