theme = "tokyonight"

[editor]
line-number = "relative"
cursorline = true
rulers = [80, 120]
bufferline = "multiple"
color-modes = true
mouse = false
auto-pairs = false
auto-format = false
true-color = true
end-of-line-diagnostics = "hint"
default-yank-register = "+"

[editor.inline-diagnostics]
other-lines = "error"
cursor-line = "error"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
# git-ignore = false

[keys.normal]
"|" = "align_selections"
x = "select_line_below"
X = "select_line_above"
C-v = "copy_selection_on_next_line"
C-s = ":w"
C-x = ":bc"
C-f = ":fmt"
C-r = ":reflow"
A-down = "page_cursor_half_down"
A-up = "page_cursor_half_up"
C-A-left = "goto_first_nonwhitespace"
C-A-right = "goto_line_end"
C-A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
"A-/" = [
    ":write-all",
    ":insert-output scooter --no-stdin >/dev/tty",
    ":redraw",
    ":reload-all"
]
C-y = [
    ":write-all",
    ":new",
    ":insert-output rm -f /tmp/yazi-chosen && yazi --chooser-file=/tmp/yazi-chosen",
    ":buffer-close!",
    ":redraw",
    ":open %sh{cat /tmp/yazi-chosen 2>/dev/null || true}",
    ":reload-all"
]

[keys.normal.g]
up = "goto_file_start"
down = "goto_last_line"
left = "goto_line_start"
right = "goto_line_end"

[keys.normal.space]
"'" = "no_op"
"." = "last_picker"
f = "file_picker_in_current_directory"
F = "file_picker"
