[language-server.typescript-language-server.config]
disableAutomaticTypingAcquisition = true
insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true

[language-server.biome]
command = "npm"
args = ["exec", "@biomejs/biome", "lsp-proxy"]

[[language]]
name = "nunjucks"
scope = "text.html.nunjucks"
injection-regex = "nunjucks"
file-types = ["njk", "tpl"]
indent = { tab-width = 2, unit = "  " }
grammar = "jinja2"

[[language]]
name = "css"
language-servers = [ { name = "vscode-css-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
