[language-server.typescript-language-server.config]
disableAutomaticTypingAcquisition = true
insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true

[language-server.typos]
command = "typos-lsp"
environment = {"RUST_LOG" = "error"}
config.config = "~/.config/typos/typos.toml"
config.diagnosticSeverity = "Info"

[language-server.biome]
command = "npm"
args = ["exec", "@biomejs/biome", "lsp-proxy"]

[[language]]
name = "nunjucks"
scope = "text.html.nunjucks"
injection-regex = "nunjucks"
file-types = ["njk", "tpl"]
indent = { tab-width = 2, unit = "  " }
grammar = "jinja2"
language-servers = ["typos"]

[[language]]
name = "markdown"
language-servers = ["typos"]

[[language]]
name = "devicetree"
file-types = ["keymap"]

[[language]]
name = "html"
language-servers = [
  { name = "vscode-html-language-server", except-features = [ "format" ] },
  "biome",
  "typos",
]
auto-format = true

[[language]]
name = "css"
language-servers = [
  { name = "vscode-css-language-server", except-features = [ "format" ] },
  "biome",
  "typos",
]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "biome",
  "typos",
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "biome",
  "typos",
]
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "biome",
  "typos",
]
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "biome",
  "typos",
]
auto-format = true

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [ "format" ] },
  "biome",
  "typos",
]
