gui:
  timeFormat: 2006-01-02
  shortTimeFormat: 15:04

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
